<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <EmbeddedResource Include="Messages.en.json" WithCulture="false" LogicalName="DvdaMaker.Localization.Messages.en.json" />
    <EmbeddedResource Include="Messages.ja.json" WithCulture="false" LogicalName="DvdaMaker.Localization.Messages.ja.json" />
  </ItemGroup>
</Project>
