<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>DvdaMaker.SurcodeTool</AssemblyName>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DvdaMaker.Processes\DvdaMaker.Processes.csproj" />
    <EmbeddedResource Include="Native\win-x64\mlp_encoder.dll" LogicalName="DvdaMaker.MlpEncoder.Library" />
  </ItemGroup>
</Project>
