#!/usr/bin/env python3
"""Regenerate the ordinal case map from the frozen migration reference data.

The baseline was measured against .NET 10.0.12; updating it requires a separate
reference check. Regeneration and application builds require no .NET runtime.
"""
import argparse
import hashlib
import json
from pathlib import Path


def generate(args):
    root = Path(__file__).resolve().parents[2]
    source = Path(args.reference or root / "tools/win-build/devdata/ordinal-case").resolve()
    reference = json.loads((source / "reference.json").read_text(encoding="utf-8"))
    mappings = [tuple(int(value, 16) for value in line.split())
                for line in (source / "mappings.tsv").read_text().splitlines()]
    ranges = []
    index = 0
    while index < len(mappings):
        start, upper = mappings[index]
        end, step, delta = start, 1, upper - start
        index += 1
        if (index < len(mappings) and mappings[index][0] - end in (1, 2)
                and mappings[index][1] - mappings[index][0] == delta):
            step = mappings[index][0] - end
            while (index < len(mappings) and mappings[index][0] - end == step
                   and mappings[index][1] - mappings[index][0] == delta):
                end = mappings[index][0]
                index += 1
        ranges.append((start, end, step, delta))
    expected = dict(mappings)
    packed = bytearray()
    digest = 0xcbf29ce484222325
    for scalar in range(0x110000):
        if 0xd800 <= scalar <= 0xdfff:
            continue
        data = expected.get(scalar, scalar).to_bytes(4, "little")
        packed.extend(data)
        for byte in data:
            digest = ((digest ^ byte) * 0x100000001b3) & 0xffffffffffffffff
    assert hashlib.sha256(packed).hexdigest().upper() == reference["CanonicalU32LeSha256"]
    expanded = {point: point + delta for start, end, step, delta in ranges
                for point in range(start, end + 1, step)}
    assert expanded == expected
    output = Path(args.output or root / "rust/crates/dvda-native/src/files/ordinal_case.rs")
    output.parent.mkdir(parents=True, exist_ok=True)
    header = f"""// Generated by tools/win-build/generate-ordinal-case.py; do not edit the table.
// Reference: local .NET {reference['Runtime']} StringComparer.OrdinalIgnoreCase (ICU mode).
// Source algorithm: dotnet/runtime v10.0.0, System/Globalization/OrdinalCasing.Icu.cs
// https://github.com/dotnet/runtime/blob/v10.0.0/src/libraries/System.Private.CoreLib/src/System/Globalization/OrdinalCasing.Icu.cs
// Frozen reference data: tools/win-build/devdata/ordinal-case (measured from the
// runtime and verified with public StringComparer for {reference['Scalars']:,} valid scalars).
// Unlisted scalars remain unchanged; no full case folding or character expansion.
// The migration baseline is pinned instead of varying with Windows/Rust updates.
// Canonical mapped scalars, little-endian u32, SHA-256:
// {reference['CanonicalU32LeSha256']}
// {len(mappings)} non-identity mappings compressed into {len(ranges)} disjoint stride ranges.

pub(super) fn uppercase(character: char) -> u32 {{
    let scalar = character as u32;
    if character.is_ascii() {{
        return character.to_ascii_uppercase() as u32;
    }}
    let index = RANGES.partition_point(|&(_, end, _, _)| end < scalar);
    if let Some(&(start, _, step, delta)) = RANGES.get(index)
        && scalar >= start
        && (scalar - start).is_multiple_of(step)
    {{
        return (scalar as i32 + delta) as u32;
    }}
    scalar
}}

// Inclusive start, inclusive end, stride, uppercase delta.
const RANGES: &[(u32, u32, u32, i32)] = &[
"""
    rows = "".join(f"    (0x{start:x}, 0x{end:x}, {step}, {delta}),\n"
                   for start, end, step, delta in ranges)
    footer = f"""];

#[cfg(test)]
mod tests {{
    #[test]
    fn all_unicode_scalar_mappings_match_frozen_dotnet_reference() {{
        // Independent digest from .NET, including identity mappings.
        let mut digest = 0xcbf29ce484222325u64;
        let mut changed = 0;
        for scalar in 0..=0x10ffff {{
            if let Some(character) = char::from_u32(scalar) {{
                let upper = super::uppercase(character);
                changed += usize::from(scalar != upper);
                for byte in upper.to_le_bytes() {{
                    digest = (digest ^ u64::from(byte)).wrapping_mul(0x100000001b3);
                }}
            }}
        }}
        assert_eq!(changed, {len(mappings)});
        assert_eq!(digest, 0x{digest:016x});
    }}
}}
"""
    output.write_text(header + rows + footer, encoding="utf-8")
    print(json.dumps({"output": str(output), "ranges": len(ranges), "reference": reference}, indent=2))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference", help="Frozen mappings.tsv and reference.json directory")
    parser.add_argument("--output", help="Generated Rust mapping module")
    generate(parser.parse_args())
