<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>dvda-toolchain</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DvdaMaker.FontTool\DvdaMaker.FontTool.csproj" />
    <EmbeddedResource Include="NativeOptimizationProfile.json" LogicalName="DvdaMaker.NativeOptimizationProfile" />
    <EmbeddedResource Include="MinimalFfmpegProfile.json" LogicalName="DvdaMaker.MinimalFfmpegProfile" />
  </ItemGroup>
</Project>
